/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/knowledge` | `/knowledge`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/progressAnalytics` | `/progressAnalytics`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/protocolLogger` | `/protocolLogger`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/secretMode` | `/secretMode`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/knowledge` | `/knowledge`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/progressAnalytics` | `/progressAnalytics`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/protocolLogger` | `/protocolLogger`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/secretMode` | `/secretMode`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/explore${`?${string}` | `#${string}` | ''}` | `/explore${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/knowledge${`?${string}` | `#${string}` | ''}` | `/knowledge${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/progressAnalytics${`?${string}` | `#${string}` | ''}` | `/progressAnalytics${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/protocolLogger${`?${string}` | `#${string}` | ''}` | `/protocolLogger${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/secretMode${`?${string}` | `#${string}` | ''}` | `/secretMode${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/knowledge` | `/knowledge`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/progressAnalytics` | `/progressAnalytics`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/protocolLogger` | `/protocolLogger`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/secretMode` | `/secretMode`; params?: Router.UnknownInputParams; } | `/+not-found${`?${string}` | `#${string}` | ''}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
